### ISSUE TITLE
Henticore packs - dead links

### ISSUE THREAD

**Issue by robertybob** [Callsign-Dingo-7/UK-Happy-Hardcore-Resources#3]
Packs 1 and 2 go to Soundcloud pages that now no longer exist. 

Are they hosted elsewhere? How could they now be shared?

**Comment by Callsign-Dingo-7** [comment]
Following up on this,

I reached out to Oxygenetix thru Discord and didn't have much success. I'm reaching out thru email on their OxyDSP site to see if that has any better results.

If Oxygenetix is not willing to fix the links, I may consider creating torrents for them, but I'd like to get permission from them before I go and do that.

In any case, I hope that we can find a way to upload the material so it does not remain lost.

**Comment by Callsign-Dingo-7** [comment]
I created torrents for the links, I'll look into having some peeps test them and let me know if they can download it.
